apiVersion: apps/v1                       # API version for Deployment resource
kind: Deployment                           # Resource type: Deployment
metadata:
  name: mysql                              # Name of the Deployment
  namespace: expense                       # Namespace where the Deployment is created
  labels:
    app: mysql                             # Label to identify the application
    tier: db                               # Label to identify the tier of the application
    project: expense                       # Label for project name

spec:
  replicas: 2                              # Number of Pod replicas to be created
  selector:
    matchLabels:                           # Labels to match for selecting Pods
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:                              # Labels assigned to the Pods
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql                        # Container name within the Pod
        image: mahalakshmi2997/mysql:v1    # Container image to use
---
apiVersion: v1                             # API version for Service resource
kind: Service                              # Resource type: Service
metadata:
  name: mysql                              # Name of the Service
  namespace: expense                       # Namespace where the Service is created
spec:
  selector:
    app: mysql                             # Matches Pods with these labels
    tier: db
    project: expense
  ports:
  - name: mysql-port                       # Name of the Service port
    protocol: TCP                          # Protocol used for the Service (TCP)
    port: 3306                             # Port on which the Service is exposed
    targetPort: 3306                       # Port on the container to which the Service forwards traffic
